spring:
  application:
    name: webstore

  datasource:
    url : jdbc:mariadb://localhost:3306/webstore
    username: webstore_app
    password: ToinenSalasana456!

  jpa:
    hibernate:
      ddl_auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true


